name = "popion-store"
main = "src/index.js"
compatibility_date = "2026-09-13"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "popion-db"
database_id = "ce619974-e9c3-401b-98f2-a01ed046845a"

[vars]
ADMIN_USER = "admin"
ADMIN_PASSWORD = "CHANGE_THIS_PASSWORD"

